services:
  - type: web
    name: verinews-backend
    env: docker
    rootDir: ./backend
    plan: free
    envVars:
      - key: TAVILY_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
